version: '3.8'

services:
  # MongoDB database
  mongodb:
    image: mongo:6.0
    container_name: kodeon-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: kodeon
      MONGO_INITDB_ROOT_PASSWORD: kodeon123
    volumes:
      - mongodb_data:/data/db

  # Redis cache
  redis:
    image: redis:7.0
    container_name: kodeon-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: kodeon-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://kodeon:kodeon123@mongodb:27017/kodeon-cloud
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/app
      - /app/node_modules

  # Frontend development server
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: kodeon-frontend
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mongodb_data:
  redis_data:
