name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  profile: minimal
                  override: true

            - name: Build compiler
              run: |
                  cd compiler
                  cargo build --verbose

            - name: Run tests
              run: |
                  cd compiler
                  cargo test --verbose

            - name: Check formatting
              run: |
                  cd compiler
                  rustup component add rustfmt
                  cargo fmt -- --check

            - name: Run clippy
              run: |
                  cd compiler
                  rustup component add clippy
                  cargo clippy -- -D warnings
